# Site settings
title: Gerry Shaw's Home Page
tag_text: Gerry Shaw
description: Gerry Shaw is a professional software engineer in Vancouver, Canada.
url: https://gshaw.ca

# Build settings
markdown: kramdown

kramdown:
  input: GFM

exclude: [
  "Gemfile.lock",
  "Gemfile",
  "LICENSE",
  "README.md"
]

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
