# Site settings
title: Gerry Shaw
description: Gerry Shaw is a professional software engineer in Vancouver, Canada.
url: https://gshaw.ca
start_year: 2013
author:
  name: Gerry Shaw
  email: gerry_shaw@yahoo.com

# Build settings
markdown: kramdown
permalink: pretty

kramdown:
  input: GFM

exclude: [
  "cspell.config.yaml",
  "Gemfile.lock",
  "Gemfile",
  "LICENSE",
  "README.md"
]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
