# Site settings
title: Gerry Shaw's Home Page
tag_text: Gerry Shaw
description: Gerry Shaw is a professional software developer in Vancouver, Canada.
url: "http://127.0.0.1:4000"

# Build settings
markdown: kramdown

exclude: ["README.md"]
